name: Build and deploy Next.js app to Azure Web App - devjobsui

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Prepare output folder for deployment
        run: |
          mkdir site
          cp -r .next public node_modules package.json next.config.js site/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_260DB0639E464A8C919A0E7BAF30C421 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7C4A5035159E4ADAA23932782752E668 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3F9359F5B914C8BA59C105E6821D128 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'devjobsui'
          slot-name: 'Production'
          package: site
